feat: Allow customizing serverTaskClasspath
We sometimes see this exception

```
2025-05-24 17:36:08.729+0000 [id=42]        WARNING hudson.model.Queue#load: Failed to load the queue file /Users/rsomasunderam/src/bb/CISYS/nflx-webservice-api-plugin/work/queue.xml
    java.lang.ClassNotFoundException: com/ctc/wstx/stax/WstxInputFactory
```

Fixing it requires adding this to dependencies

```
serverTaskClasspath "org.codehaus.woodstox:wstx-asl:3.2.7"
```

To support that, we need the `serverTaskClasspath` to support such a mode of execution.